### ISSUE TITLE
fbgemm_gpu_py.so: undefined symbol: _ZN3c1021getCustomClassTypeMapEv

### ISSUE THREAD

**Issue by zxgx** [pytorch/FBGEMM#1117]
Hi, I met above error while I was trying to run the [dlrm with torchrec](https://github.com/facebookresearch/dlrm/tree/main/torchrec_dlrm), and the traceback was similar to https://github.com/pytorch/torchrec/issues/319#issue-1233368969.
Does anybody know how to fix this error?

**Comment by geyyer** [comment]
Hi @zxgx, thanks for sharing! It is a known issue related to pypi limits for the torchrec repo. If this is an immediate problem, you could go back to torchrec stable (torchrec package). You could also build from source. Please let us know if it worked for you!

**Comment by geyyer** [comment]
Looks like the issue is not resurfacing any longer, closing

**Comment by DeepakSaini119** [comment]
Hi @geyyer I encounter similar error `fbgemm_gpu_py.so: undefined symbol: _ZN3c104cuda9SetDeviceEi` and then finally `AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'` when trying to import fbgemm_gpu. My system specifications:
- Ubuntu 20.04
- CUDA 11.6
- python 3.10
- torch nightly 2.0.0.dev20230202+cu116
- fbgemm-gpu-nightly fbgemm-gpu-nightly-2023.6.27

Any suggestions on how to fix this?

**Comment by q10** [comment]
Errors of the signature `AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'` generally means that there is a shared library required by FBGEMM_GPU that is missing from the path.  Could you expand the paste of the error message?  Usually the missing library of interest should be pointed out in the message body.

**Comment by DeepakSaini119** [comment]
Thanks @q10, the full error trace is:
```python
>>> import fbgemm_gpu
/home/user/miniconda3/envs/torchrec/lib/python3.10/site-packages/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/torchrec/lib/python3.10/site-packages/torch/_ops.py", line 562, in __getattr__
    op, overload_names = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator fbgemm::jagged_2d_to_dense

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/torchrec/lib/python3.10/site-packages/fbgemm_gpu/__init__.py", line 21, in <module>
    from . import _fbgemm_gpu_docs  # noqa: F401, E402
  File "/home/user/miniconda3/envs/torchrec/lib/python3.10/site-packages/fbgemm_gpu/_fbgemm_gpu_docs.py", line 19, in <module>
    torch.ops.fbgemm.jagged_2d_to_dense,
  File "/home/user/miniconda3/envs/torchrec/lib/python3.10/site-packages/torch/_ops.py", line 566, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'
```

**Comment by q10** [comment]
CUDA 11.6 is likely an issue, since we don't officially support it.  Would it be possible for you to try a CUDA 11.7 or 11.8 installation (Conda is usually the easiest way to install the packages) and let me know how it goes?

**Comment by DeepakSaini119** [comment]
Thanks @q10 , works perfectly with CUDA 11.8. However I still get the error described in this issue: https://github.com/pytorch/FBGEMM/issues/1847
