### ISSUE TITLE
‘_mm256_cmpge_epi32_mask’ was not declared for fbgemm when compiling CPU only pytorch

### ISSUE THREAD

**Issue by zengzengsun** [pytorch/FBGEMM#647]
When I compile CPU only pytorch, I encountered below issue for fbgemm module:
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc: In function ‘void fbgemm::internal::compressed_indices_remap_avx512(int32_t, const IndexType*, const int32_t*, const IndexType*, const float*, IndexType*, IndexType*, float*)’:
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:441:66: error: there are no arguments to ‘_mm256_cmpge_epi32_mask’ that depend on a template parameter, so a declaration of ‘_mm256_cmpge_epi32_mask’ must be available [-fpermissive]
__mmask8 cmp_res_v = _mm256_cmpge_epi32_mask(len_v, vec_len_v);
^
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:441:66: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:476:59: error: there are no arguments to ‘_mm256_cmpge_epi32_mask’ that depend on a template parameter, so a declaration of ‘_mm256_cmpge_epi32_mask’ must be available [-fpermissive]
cmp_res_v = _mm256_cmpge_epi32_mask(len_v, vec_len_v);
^
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc: In instantiation of ‘void fbgemm::internal::compressed_indices_remap_avx512(int32_t, const IndexType*, const int32_t*, const IndexType*, const float*, IndexType*, IndexType*, float*) [with IndexType = int; bool HAS_WEIGHTS = true; int32_t = int]’:
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:595:1: required from here
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:441:49: error: ‘_mm256_cmpge_epi32_mask’ was not declared in this scope
__mmask8 cmp_res_v = _mm256_cmpge_epi32_mask(len_v, vec_len_v);
^
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:476:42: error: ‘_mm256_cmpge_epi32_mask’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
cmp_res_v = _mm256_cmpge_epi32_mask(len_v, vec_len_v);
^
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:441:49: note: ‘_mm256_cmpge_epi32_mask’ declared here, later in the translation unit
__mmask8 cmp_res_v = _mm256_cmpge_epi32_mask(len_v, vec_len_v);
^
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc: In instantiation of ‘void fbgemm::internal::compressed_indices_remap_avx512(int32_t, const IndexType*, const int32_t*, const IndexType*, const float*, IndexType*, IndexType*, float*) [with IndexType = int; bool HAS_WEIGHTS = false; int32_t = int]’:
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:596:1: required from here
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:441:49: error: ‘_mm256_cmpge_epi32_mask’ was not declared in this scope
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:476:42: error: ‘_mm256_cmpge_epi32_mask’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
cmp_res_v = _mm256_cmpge_epi32_mask(len_v, vec_len_v);
^
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:441:49: note: ‘_mm256_cmpge_epi32_mask’ declared here, later in the translation unit
__mmask8 cmp_res_v = _mm256_cmpge_epi32_mask(len_v, vec_len_v);
^
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc: In instantiation of ‘void fbgemm::internal::compressed_indices_remap_avx512(int32_t, const IndexType*, const int32_t*, const IndexType*, const float*, IndexType*, IndexType*, float*) [with IndexType = long int; bool HAS_WEIGHTS = true; int32_t = int]’:
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:597:1: required from here
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:441:49: error: ‘_mm256_cmpge_epi32_mask’ was not declared in this scope
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:476:42: error: ‘_mm256_cmpge_epi32_mask’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
cmp_res_v = _mm256_cmpge_epi32_mask(len_v, vec_len_v);
^
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:441:49: note: ‘_mm256_cmpge_epi32_mask’ declared here, later in the translation unit
__mmask8 cmp_res_v = _mm256_cmpge_epi32_mask(len_v, vec_len_v);
^
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc: In instantiation of ‘void fbgemm::internal::compressed_indices_remap_avx512(int32_t, const IndexType*, const int32_t*, const IndexType*, const float*, IndexType*, IndexType*, float*) [with IndexType = long int; bool HAS_WEIGHTS = false; int32_t = int]’:
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:598:1: required from here
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:441:49: error: ‘_mm256_cmpge_epi32_mask’ was not declared in this scope
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:476:42: error: ‘_mm256_cmpge_epi32_mask’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
cmp_res_v = _mm256_cmpge_epi32_mask(len_v, vec_len_v);
^
/home/sunrise/pytorch/third_party/fbgemm/src/EmbeddingSpMDMAvx512.cc:441:49: note: ‘_mm256_cmpge_epi32_mask’ declared here, later in the translation unit
__mmask8 cmp_res_v = _mm256_cmpge_epi32_mask(len_v, vec_len_v);

Could anyone provide help?

**Comment by imaginary-person** [comment]
Which compiler & what version of it are you using?

**Comment by zengzengsun** [comment]
> Which compiler & what version of it are you using?

here is my compiler info:
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

**Comment by dskhudia** [comment]
Seems like gcc 5.4 doesn't have the intrinsic _mm256_cmpge_epi32_mask  implemented. 

Code containing _mm256_cmpge_epi32_mask works with 5.5 but doesn't with gcc 5.4 : https://godbolt.org/z/f5bsrrjW1

Could you use a more recent version of compiler?

**Comment by malfet** [comment]
Hmm, but to be fair, FBGEMM cmake scripts should detect whether AVX512 support is available and skip respective codeparts

**Comment by dskhudia** [comment]
AVX512 support is available but it seems gcc 5.4 has missing intrinsic APIs.

**Comment by dskhudia** [comment]
@malfet, do we build Pytorch with gcc 5.4 in CI?

**Comment by malfet** [comment]
@dskhudia, no we do not, but it doesn't mean we should not check wether or not compiler extensions we want to use is available.

**Comment by dskhudia** [comment]
@malfet Agreed. Just want to make sure that the minimum version of gcc supported by PyTorch is also supported by FBGEMM. Do you happen to know the minimum version of gcc supported by PyTorch?

**Comment by dskhudia** [comment]
Actually just searched about it a bit more and found that it's a gcc bug. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79932
Essentially the code works if compiled under -Og, -O2, or -O3 but fails with -O0.

The fix is back ported to gcc 5.5 but not to 5.4.

**Comment by zengzengsun** [comment]
> 
> 
> Actually just searched about it a bit more and found that it's a gcc bug. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79932
> Essentially the code works if compiled under -Og, -O2, or -O3 but fails with -O0.
> 
> The fix is back ported to gcc 5.5 but not to 5.4.

@dskhudia yes~ you're right. I was just going to tell you that the issue is only happened in debug building.
Thanks all guys for this issue
